name: Continious Integration

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run:  dotnet build --configuration Release
      working-directory: ./
    - name: Test
      run:  dotnet test
      working-directory: ./
    - name: Build and deploy package
      run: dotnet publish -r win-x64 -c Release --self-contained false
    
     
     
     
      
      
